[package]
name = "cryptopad"
version = "0.1.0"
authors = ["Connor Brewster <connor.brewster@eagles.oc.edu>"]
edition = "2018"

[dependencies]
aes = "0.3.1"
block-modes = "0.2.0"
rand = "0.5.5"
sha2 = "0.8.0"

[dev-dependencies]
hex-literal = "0.1.1"
